- name: Check the Presence of Deployment Destination
  stat: path=/var/www
  register: deploy_dir

- name: Make the Destination Directory If It Does Not Exist
  become: yes
  become_method: sudo
  file: path=/var/www state=directory
  when: deploy_dir.stat.isdir is not defined

- name: Change the Ownewrship of the Destination Directory
  become: yes
  become_method: sudo
  file: path=/var/www state=directory group={{ ansible_ssh_user }} owner={{ ansible_ssh_user }}
