default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: <%= ENV.fetch("DATABASE_HOST", 'localhost') %>
  port: <%= ENV.fetch("DATABASE_PORT", 3306) %>
  username: <%= ENV.fetch("DATABASE_USERNAME", 'root') %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", 'password') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  collation: utf8mb4_general_ci

development:
  <<: *default
  database: rails_seed_development
  local_infile: true

test:
  <<: *default
  database: rails_seed_test
  local_infile: true

demo:
  <<: *default
  database: rails_seed_demo

staging:
  <<: *default
  database: rails_seed_staging

preview:
  <<: *default
  database: rails_seed_preview

production:
  <<: *default
  database: rails_seed_production
